name: Build and Publish image to Docker Hub
on:
  push:
    branches: 
      - main
   paths:
      - 'api/Dockerfile'
      - 'front-end-nextjs/Dockerfile'
  pull_request:
    branches: [ "main" ]

jobs:
 publish_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: checkout
      run: 
        docker build ./api/ -t jothisram/freelancer-hub-mern-client:latest
        docker build ./front-end-nextjs/ -t  jothisram/freelancer-hub-mern-server:latest
    - name: push image to docker hub
      run: 
        docker login -u jothisram -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker push jothisram/freelancer-hub-mern-client:latest
        docker push jothisram/freelancer-hub-mern-server:latest
        
 
