name: MongoDB Website Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v3

      - name: Build Website
        run: npm run build

      - name: Run Tests
        run: npm test
